const blogPosts = [
  {
    title: "The Future of AI in Daily Life",
    author: "Jane Doe",
    image: "ai-future.jpg",
    description: "Exploring how AI is shaping the future of work and home.",
    date: "2025-03-29",
  },
  {
    title: "Top 10 Travel Destinations in 2025",
    author: "John Smith",
    image: "travel-2025.jpg",
    description: "Discover the must-visit places for your next vacation.",
    date: "2025-03-28",
  },
  {
    title: "Healthy Eating on a Budget",
    author: "Alice Johnson",
    image: "healthy-food.jpg",
    description:
      "Tips and tricks for eating nutritious meals without breaking the bank.",
    date: "2025-03-27",
  },
  {
    title: "The Rise of Electric Vehicles",
    author: "Michael Brown",
    image: "ev-rise.jpg",
    description: "How EVs are changing the automotive industry.",
    date: "2025-03-26",
  },
  {
    title: "Mastering Remote Work",
    author: "Emily White",
    image: "remote-work.jpg",
    description:
      "Best practices for staying productive while working from home.",
    date: "2025-03-25",
  },
  {
    title: "Photography Tips for Beginners",
    author: "David Clark",
    image: "photography-tips.jpg",
    description: "A beginner's guide to capturing stunning photos.",
    date: "2025-03-24",
  },
  {
    title: "The Power of Meditation",
    author: "Sophia Green",
    image: "meditation.jpg",
    description: "How daily meditation can improve your mental health.",
    date: "2025-03-23",
  },
  {
    title: "Investing in Cryptocurrency",
    author: "Robert Black",
    image: "crypto-invest.jpg",
    description: "A beginner's guide to understanding the crypto market.",
    date: "2025-03-22",
  },
  {
    title: "Best Home Workout Routines",
    author: "Laura Adams",
    image: "home-workout.jpg",
    description: "Effective exercises to keep you fit at home.",
    date: "2025-03-21",
  },
  {
    title: "Sustainable Fashion Trends",
    author: "Emma Wilson",
    image: "sustainable-fashion.jpg",
    description: "How to build a stylish and eco-friendly wardrobe.",
    date: "2025-03-20",
  },
  {
    title: "How to Start a Podcast",
    author: "James Miller",
    image: "start-podcast.jpg",
    description: "Step-by-step guide to launching your own podcast.",
    date: "2025-03-19",
  },
  {
    title: "The Science of Happiness",
    author: "Olivia Turner",
    image: "happiness-science.jpg",
    description: "Understanding what makes us happy according to research.",
    date: "2025-03-18",
  },
  {
    title: "Top 5 Coding Languages in 2025",
    author: "William Scott",
    image: "coding-languages.jpg",
    description: "A look at the most in-demand programming languages.",
    date: "2025-03-17",
  },
  {
    title: "Mindfulness for a Stress-Free Life",
    author: "Hannah Lee",
    image: "mindfulness.jpg",
    description: "How practicing mindfulness can reduce stress.",
    date: "2025-03-16",
  },
  {
    title: "The Best Books to Read This Year",
    author: "Daniel Harris",
    image: "best-books.jpg",
    description: "Must-read books that will keep you inspired.",
    date: "2025-03-15",
  },
  {
    title: "How to Monetize Your Blog",
    author: "Chris Evans",
    image: "monetize-blog.jpg",
    description:
      "Different strategies to turn your blog into a source of income.",
    date: "2025-03-14",
  },
  {
    title: "The Ultimate Guide to Digital Marketing",
    author: "Rebecca Foster",
    image: "digital-marketing.jpg",
    description: "Essential digital marketing strategies for businesses.",
    date: "2025-03-13",
  },
  {
    title: "Gaming Trends to Watch in 2025",
    author: "Jason Carter",
    image: "gaming-trends.jpg",
    description: "A look at what's next in the gaming industry.",
    date: "2025-03-12",
  },
  {
    title: "Personal Finance Tips for Young Adults",
    author: "Megan Brooks",
    image: "personal-finance.jpg",
    description: "Smart money habits to build a strong financial future.",
    date: "2025-03-11",
  },
  {
    title: "The Future of Space Exploration",
    author: "Ryan Stewart",
    image: "space-exploration.jpg",
    description: "What's next for humanity in outer space?",
    date: "2025-03-10",
  },
];

module.exports = { data: blogPosts };
